#1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. how does it ehance Python's capabilities for numerical operations?
   Numpy is powerful library that provides efficient and optimized array operationsmaking it a go-to tool for numerical python.
   Its advantages are it has higher execution speed and uses less memory space because of its contiguous memory location.

#2.Compare and contrast np.mean() and np.average() functions in NumPy. when would you use one over the other?
   np.mean() gives you simply a arithmetic mean whereas in np.average you calculate arithmetic mean and weighted average calculation by passing a specific argument if you don't use it will simply calculate average mean. If you want calculate only simply average mean you should go with np.mean().

#3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
  The NumPy.flip() reverses a order of array element along the specified axis , preserving the shape of an array. and list slicing methods also works.

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6]) #By using flip() function
rev = np.flip(arr)
print(rev)

[6 5 4 3 2 1]


In [4]:
sli = arr[::-1] #By using list slicing
print(sli)

[6 5 4 3 2 1]


#4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memort management and performance.
   By using a dtype attribute you can know the datatype . If datatype is homogenous it will store in contiguos location it will make all the operation smoother.

#5.Define ndarrays in NumPy and explain their key features.How do they differ from standard Python lists?
   An ndarray is a multi-dimensional arrays of the same type and size.
   Python list contain any type of data for example integer, string, float, boolean,complex number etc whereas ndarray contains same data type for faster execution.

#6.Analyze the performane benefits of NumPy arrays of Python lists for large scale numerical operations.
   Numpy arrays provide a significantly faster speed over python traditional list its because NumPy built in C and uses pre compiled code for numerical operations.

#7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
   hstack function is used to stack the sequence of input arrays horizontally (colum wise).
   vstack function is used to stack the sequence of input arrays verical (row wise).

In [5]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr3=np.array([["a","b","c"],["d","e","f"]])

In [8]:
arrh=np.hstack([arr1,arr2,arr3]) #stack horizontally
print(arrh)

[['1' '2' '3' '7' '8' '9' 'a' 'b' 'c']
 ['4' '5' '6' '10' '11' '12' 'd' 'e' 'f']]


In [9]:
arrv=np.vstack([arr1,arr2,arr3]) #stack verically
print(arrv)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['10' '11' '12']
 ['a' 'b' 'c']
 ['d' 'e' 'f']]


#8.Explain the difference between fliplr() and flipud() methods in NumPy ,including their effects on various array dimensions.
   fliplr() flip elements horizontally or left to right.
   flipud() flip elements vertically or upside down.
   In case of 1-D array flipud() doesn't have any impact.   

In [13]:
p1=np.arange(9).reshape(3,3)
print(p1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
p2=np.fliplr(p1) #flip elements horizontally
print(p2)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [16]:
p3=np.flipud(p1) #flip elements vertically
print(p3)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [18]:
q1 = np.array([1,2,3,4,5,6])
q2=np.fliplr([q1])
print(q2)

[[6 5 4 3 2 1]]


In [19]:
q3=np.flipud([q1])
print(q3)

[[1 2 3 4 5 6]]


#9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
  array_split function divide array into given number of enequal parts.Let's understand with example.

In [20]:
array = np.arange(15)

In [24]:
#split arrays into two equal parts.
sp4=np.array_split(array,4)
print(sp4)

[array([0, 1]), array([2, 3]), array([4]), array([5])]


#10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
   Vectorization is a method to performing array operations without use of loops.
   Broadcasting provides a means of vectorizing array operations so that looping occurs in c instead of python.that makes operations efficient.

#**PRACTICAL QUESTIONS**

#1.Create a 3X3 NumPy array with random integers between 1 to 100.Then, interchange its rows and columns.

In [27]:
m1=np.random.randint(1,101,(3,3))
print(m1)

[[56  9 48]
 [57 77 51]
 [74 84 43]]


In [28]:
m2=m1.T
print(m2)

[[56 57 74]
 [ 9 77 84]
 [48 51 43]]


#2.Generate a 1D NumPy array with 10 elements.Reshape it into a 2X5 array,then into 5X2 array.

In [30]:
n1=np.random.randint(1,15,(1,10))
print(n1)

[[ 3 10  9  6  8  6 12  5  7  1]]


In [31]:
ns=n1.reshape(2,5)
print(ns)

[[ 3 10  9  6  8]
 [ 6 12  5  7  1]]


In [32]:
nq=n1.reshape(5,2)
print(nq)

[[ 3 10]
 [ 9  6]
 [ 8  6]
 [12  5]
 [ 7  1]]


#3.Create a 4X4 NumPy array with random float values.Add a border of zeros around it, resulting in a 6X6 array.

In [34]:
a1=np.random.rand(4,4)
print(a1)

[[0.23039282 0.09639261 0.08828185 0.33358307]
 [0.10749899 0.15150769 0.01677849 0.85459977]
 [0.68248787 0.37275727 0.15161448 0.98012866]
 [0.01895076 0.45345383 0.62521168 0.02488398]]


In [35]:
bordered_array=np.pad(a1,pad_width=1,mode='constant',constant_values=0)
print(bordered_array)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.23039282 0.09639261 0.08828185 0.33358307 0.        ]
 [0.         0.10749899 0.15150769 0.01677849 0.85459977 0.        ]
 [0.         0.68248787 0.37275727 0.15161448 0.98012866 0.        ]
 [0.         0.01895076 0.45345383 0.62521168 0.02488398 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [37]:
b1=np.arange(10,61,5)
print(b1)

[10 15 20 25 30 35 40 45 50 55 60]


#5.Create a NumPy array of string ['python','numpy','pandas'].Apply different case of transformations (uppercase,lowercase,title case,etc.) to each element.

In [39]:
c1=np.array(['python','numpy','pandas'])
c2=np.char.upper(c1) #for uppercase
print(c2)

['PYTHON' 'NUMPY' 'PANDAS']


In [40]:
c3=np.char.lower(c1) #for lowercase
print(c3)

['python' 'numpy' 'pandas']


In [41]:
c4=np.char.title(c1) #for titlecase
print(c4)

['Python' 'Numpy' 'Pandas']


#6.Generate an NumPy array of words .Insert a space between each character of every word in the array.

In [42]:
words=np.array(['hello','world','numpy','array','space'])
spaced_words=np.char.join(" ",words)
print(spaced_words)

['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y' 's p a c e']


#7.Create two 2D NumPy arrays and perform element wise addition-wise addition, subtraction, multiplication, and division.

In [43]:
d1=np.array([[1,2,3],[4,5,6]])
d2=np.array([[7,8,9],[10,11,12]])
print(d1+d2) #element wise addition

[[ 8 10 12]
 [14 16 18]]


In [44]:
print(d1-d2) #element wise subtraction

[[-6 -6 -6]
 [-6 -6 -6]]


In [45]:
print(d1*d2) #element wise multiplication

[[ 7 16 27]
 [40 55 72]]


In [46]:
print(d1/d2) #element wise division

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [48]:
i1=np.eye(5)

In [49]:
print(i1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [50]:
diagonal_elements=np.diag(i1)
print(diagonal_elements)

[1. 1. 1. 1. 1.]


#9.Generate a NumPy array of 100 random integers between 0 and 1000.Find and display all prime numbers in this array.

In [57]:
e1=np.random.randint(0,1001,100)

#create a function to check number is prime of not
def is_prime(n):
  if n<=1:
    return False
  for i in range(2,int(n**0.5)+1):
     if n % i == 0:
        return False
  return True

prime_numbers= [num for num in e1 if is_prime(num)]
print("random numpy array:",e1)
print("extract prime number numpy array:",prime_numbers)

random numpy array: [163 599 531 380 133 796 262 933  91 858 990 123  18 895 900 445 835 492
 303  53 714 438 160 308 550 745 347 819  26 759 189 906 176 983 442 473
 395  83 755 610 646  66 421 456 265 452 516 718 227 740 490 709  60 498
 706 603 227  47 493 690 458 230 183 378 442 390 565 968 168 689 271 859
 693 505 497 187 114 886 852 623 101 615 260  49 792 580 292 468 537 585
  80 697 659 724 977 769 884 707 706 995]
extract prime number numpy array: [163, 599, 53, 347, 983, 83, 421, 227, 709, 227, 47, 271, 859, 101, 659, 977, 769]


#10.Create an NumPy array representing daily temperature for a month. Calculate and display the weekly averages.

In [65]:
temp=np.array([30,34,35,34,29,28,30,36,27,28,29,31,33,32,34,34,35,30,31,28,29,34,32,27,34,32,29,32])
print("List of temperature of each day of month:",temp)

List of temperature of each day of month: [30 34 35 34 29 28 30 36 27 28 29 31 33 32 34 34 35 30 31 28 29 34 32 27
 34 32 29 32]


In [63]:
spt=np.split(temp,4)
print("Average temperature of first week:",np.mean(spt[0]))
print("Average temperature of second week:",np.mean(spt[1]))
print("Average temperature of third week:",np.mean(spt[2]))
print("Average temperature of fourth week:",np.mean(spt[3]))

Average temperature of first week: 31.428571428571427
Average temperature of second week: 30.857142857142858
Average temperature of third week: 31.571428571428573
Average temperature of fourth week: 31.428571428571427
